#!/bin/bash

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100
# python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100
# mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_100

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200
# python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200
# mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_200

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500
# python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500
# mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_500

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000
# python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000
# mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_1000

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000
# python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000
# mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_2000

python3 get_avg_returns.py 1 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000
python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000
mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000
mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000
mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000
cp play.py game.py config.json playbatch*.sh postprocess.sh o_DaisoSokcho_SAC_num_env_steps_to_collect_init_5000

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000
# python3 plot_csv.py o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000
# mkdir o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000.* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000
# mv o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000_* o_DaisoSokcho_SAC_num_env_steps_to_collect_init_10000

