#!/bin/bash

# python3 get_avg_returns.py 5 o_Reacher-v2_SAC
# python3 plot_csv.py o_Reacher-v2_SAC

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_DQN_multiagent_num_actions_3
# python3 plot_csv.py o_Reacher-v2_discrete_DQN_multiagent_num_actions_3

# python3 get_avg_returns.py 5 o_DaisoSokcho_SAC
# python3 plot_csv.py o_DaisoSokcho_SAC

# python3 get_avg_returns.py 5 o_DaisoSokcho_discrete_CDQN_multiagent_num_actions_3
# python3 plot_csv.py o_DaisoSokcho_discrete_CDQN_multiagent_num_actions_3

# python3 get_avg_returns.py 5 o_DaisoSokcho_discrete_CDQN_multiagent_num_actions_5
# python3 plot_csv.py o_DaisoSokcho_discrete_CDQN_multiagent_num_actions_5

# python3 get_avg_returns.py 5 o_DaisoSokcho_discrete_CDQN_multiagent_num_actions_7
# python3 plot_csv.py o_DaisoSokcho_discrete_CDQN_multiagent_num_actions_7

# python3 get_avg_returns.py 5 o_DaisoSokcho_discrete_DQN_multiagent_num_actions_3
# python3 plot_csv.py o_DaisoSokcho_discrete_DQN_multiagent_num_actions_3

# python3 get_avg_returns.py 5 o_DaisoSokcho_discrete_DQN_multiagent_num_actions_5
# python3 plot_csv.py o_DaisoSokcho_discrete_DQN_multiagent_num_actions_5

# python3 get_avg_returns.py 5 o_DaisoSokcho_discrete_DQN_multiagent_num_actions_7
# python3 plot_csv.py o_DaisoSokcho_discrete_DQN_multiagent_num_actions_7

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_100

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_500

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_1000

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_2000

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_3000

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_4000

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000
# python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000
# mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000
# mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_5000

python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000
python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000
mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000
mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000
mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_6000

python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000
python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000
mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000
mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000
mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_7000

python3 get_avg_returns.py 5 o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000
python3 plot_csv.py o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000
mkdir o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000
mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000.* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000
mv o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000_* o_Reacher-v2_discrete_CDQN_multiagent_num_actions_3_num_init_collect_steps_8000

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100
# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100
# python3 plot_csv.py o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100
# mkdir o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100.* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100_* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_100

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500
# python3 plot_csv.py o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500
# mkdir o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500.* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500_* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_500

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000
# python3 plot_csv.py o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000
# mkdir o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000.* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000_* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_1000

# python3 get_avg_returns.py 5 o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000
# python3 plot_csv.py o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000
# mkdir o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000.* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000
# mv o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000_* o_Reacher-v2_discrete_DQN_multiagent_num_actions_3_num_init_collect_steps_5000

